// Code generated by spicegen. DO NOT EDIT
package organization

type OrganizationPermission string

const (
	ViewAllDocumentsPermission OrganizationPermission = "view_all_documents"
)

type OrganizationRelation string

const (
	AdministratorRelation OrganizationRelation = "administrator"
)
