// Code generated by spicegen. DO NOT EDIT
package team

var ALLOWED_RELATION_SUBJECT_TYPES = map[TeamRelation]map[string]string{
	MemberRelation: {
		"user": "...",
		"team": "member",
	},
}

type TeamRelation string

const (
	MemberRelation TeamRelation = "member"
)
