// Code generated by spicegen. DO NOT EDIT
package document

type DocumentPermission string

const (
	ViewPermission DocumentPermission = "view"
)

var ALLOWED_PERMISSION_SUBJECT_TYPES = map[DocumentPermission]map[string]bool{
	ViewPermission: {
		"user": true,
	},
}

var ALLOWED_RELATION_SUBJECT_TYPES = map[DocumentRelation]map[string]string{
	DocorgRelation: {
		"organization": "...",
	},
	ReaderRelation: {
		"user": "...",
	},
	WriterRelation: {
		"user": "...",
	},
}

type DocumentRelation string

const (
	DocorgRelation DocumentRelation = "docorg"
	ReaderRelation DocumentRelation = "reader"
	WriterRelation DocumentRelation = "writer"
)
